// <auto-generated />
using System;
using CapysBakery.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapysBakery.Web.Migrations
{
    [DbContext(typeof(CapysBakeryDbContext))]
    partial class CapysBakeryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapysBakery.Web.Models.Alergeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alergeno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("alergeno", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ComentarioPublicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comentario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int")
                        .HasColumnName("id_publicacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentario_publicacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.CuentaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta_bancaria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("banco");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_cuenta");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_cuenta");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("titular");

                    b.HasKey("Id");

                    b.ToTable("cuenta_bancaria", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.EstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estado_pedido", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.HistorialEstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_pedido");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cambio");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("historial_estado_pedido", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ImagenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_imagen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit")
                        .HasColumnName("es_principal");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url_imagen");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("imagen_producto", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.Property<bool>("SoloRecoger")
                        .HasColumnType("bit")
                        .HasColumnName("solo_recoger");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("metodo_pago", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ModalidadEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_modalidad_entrega");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequiereDireccion")
                        .HasColumnType("bit")
                        .HasColumnName("requiere_direccion");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("modalidad_entrega", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.OpcionPersonalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_opcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("TipoPersonalizacionId")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_personalizacion");

                    b.HasKey("Id");

                    b.HasIndex("TipoPersonalizacionId");

                    b.ToTable("opcion_personalizacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo_pedido");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comentarios");

                    b.Property<string>("DireccionOPuntoEntrega")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("direccion_o_punto_entrega");

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_pedido");

                    b.Property<DateTime>("FechaEntregaSolicitada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_solicitada");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    b.Property<int>("ModalidadEntregaId")
                        .HasColumnType("int")
                        .HasColumnName("id_modalidad_entrega");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("telefono_cliente");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPedido")
                        .IsUnique();

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("ModalidadEntregaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("PresentacionId")
                        .HasColumnType("int")
                        .HasColumnName("id_presentacion");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PresentacionId");

                    b.ToTable("pedido_detalle", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.PedidoDetallePersonalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_personalizacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoDetalleId")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_pedido");

                    b.Property<decimal>("PrecioAdicionalUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_adicional_unitario");

                    b.Property<int>("ProductoOpcionId")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_opcion");

                    b.HasKey("Id");

                    b.HasIndex("PedidoDetalleId");

                    b.HasIndex("ProductoOpcionId");

                    b.ToTable("pedido_detalle_personalizacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPorCorreo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("creado_por_correo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<bool>("EsPromocion")
                        .HasColumnType("bit")
                        .HasColumnName("es_promocion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ProductoOpcionPersonalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto_opcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<int>("OpcionId")
                        .HasColumnType("int")
                        .HasColumnName("id_opcion");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_adicional");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("OpcionId");

                    b.HasIndex("ProductoId", "OpcionId")
                        .IsUnique();

                    b.ToTable("producto_opcion_personalizacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ProductoPresentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_presentacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Porciones")
                        .HasColumnType("int")
                        .HasColumnName("porciones");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("producto_presentacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_publicacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorCorreo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("autor_correo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("categoria");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<bool>("Publicada")
                        .HasColumnType("bit")
                        .HasColumnName("publicada");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("resumen");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("publicacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.TipoPersonalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_personalizacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipo_personalizacion", (string)null);
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("CreadaPorCorreo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("creada_por_correo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("producto_alergeno", b =>
                {
                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("id_alergeno")
                        .HasColumnType("int");

                    b.HasKey("id_producto", "id_alergeno");

                    b.HasIndex("id_alergeno");

                    b.ToTable("producto_alergeno");
                });

            modelBuilder.Entity("producto_categoria", b =>
                {
                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.HasKey("id_producto", "id_categoria");

                    b.HasIndex("id_categoria");

                    b.ToTable("producto_categoria");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ComentarioPublicacion", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.Publicacion", null)
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.HistorialEstadoPedido", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.EstadoPedido", "EstadoPedido")
                        .WithMany()
                        .HasForeignKey("EstadoPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.Pedido", null)
                        .WithMany("Historial")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPedido");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ImagenProducto", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.Producto", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapysBakery.Web.Models.OpcionPersonalizacion", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.TipoPersonalizacion", "TipoPersonalizacion")
                        .WithMany("Opciones")
                        .HasForeignKey("TipoPersonalizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPersonalizacion");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Pedido", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.EstadoPedido", "EstadoPedido")
                        .WithMany()
                        .HasForeignKey("EstadoPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.ModalidadEntrega", "ModalidadEntrega")
                        .WithMany()
                        .HasForeignKey("ModalidadEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoPedido");

                    b.Navigation("MetodoPago");

                    b.Navigation("ModalidadEntrega");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.PedidoDetalle", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.Pedido", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.ProductoPresentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.PedidoDetallePersonalizacion", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.PedidoDetalle", null)
                        .WithMany("Personalizaciones")
                        .HasForeignKey("PedidoDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.ProductoOpcionPersonalizacion", "ProductoOpcion")
                        .WithMany()
                        .HasForeignKey("ProductoOpcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoOpcion");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ProductoOpcionPersonalizacion", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.OpcionPersonalizacion", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapysBakery.Web.Models.Producto", null)
                        .WithMany("OpcionesPersonalizacion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.ProductoPresentacion", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.Producto", "Producto")
                        .WithMany("Presentaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("producto_alergeno", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.Alergeno", null)
                        .WithMany()
                        .HasForeignKey("id_alergeno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prodalerg_alergeno");

                    b.HasOne("CapysBakery.Web.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prodalerg_producto");
                });

            modelBuilder.Entity("producto_categoria", b =>
                {
                    b.HasOne("CapysBakery.Web.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prodcat_categoria");

                    b.HasOne("CapysBakery.Web.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prodcat_producto");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.PedidoDetalle", b =>
                {
                    b.Navigation("Personalizaciones");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.Producto", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("OpcionesPersonalizacion");

                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("CapysBakery.Web.Models.TipoPersonalizacion", b =>
                {
                    b.Navigation("Opciones");
                });
#pragma warning restore 612, 618
        }
    }
}
